config/routes.rb
Rails.application.routes.draw do
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: [:show, :edit, :update, :destroy]
  
  def index
    @books = Book.all
  end

  def show
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to '/books', notice: 'Created!!'
    else
      render :new
    end

  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to '/books', notice: 'Edited!!'
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to '/books', notice: 'DELETED!!!!'
  end

  private
  def book_params
    params.require(:book).permit(:title, :content, :price)
  end

  def find_book
    @book = Book.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1>New</h1>

<% if @book.errors.any? %>
  <%= @book.errors.full_messages %>
<% end %>


<%= form_for @book do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>

  <%= form.label :content %>
  <%= form.text_field :content %>

  <%= form.label :price %>
  <%= form.text_field :price %>

  <%= form.submit %>

<% end %>

app/views/books/index.html.erb
<h1>Books index</h1>

<%= link_to 'New', new_book_path %>

<table>
  <thead>
    <tr>
      <td>Title</td>
      <td>Content</td>
      <td>Price</td>
      <td>Other Function</td>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td><%= link_to book.title, book_path(book.id) %></td>
      <td><%= book.content %></td>
      <td><%= book.price %></td>
      <td><%= link_to 'edit', edit_book_path(book.id) %>
          <%= link_to 'delete', book_path(book.id), method: 'DELETE', data:{confirm: 'Are you sure!?'} %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/books/new.html.erb
<h1>New</h1>

<% if @book.errors.any? %>
  <%= @book.errors.full_messages %>
<% end %>


<%= form_for @book do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>

  <%= form.label :content %>
  <%= form.text_field :content %>

  <%= form.label :price %>
  <%= form.text_field :price %>

  <%= form.submit %>

<% end %>

app/views/books/show.html.erb
<%= @book.title %>
<div><%= @book.content %></div>
<div><%= @book.price %></div>

<%= link_to 'back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HomeworkCrud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= notice %>
    <%= yield %>
  </body>
</html>